CREATE_SERVER = 0
DELETE_SERVERS = 1
START_SERVERS = 2
STOP_SERVERS = 3
LIST_SERVERS = 4
REQUEST_LOG = 5
RENAME_AI = 6
REQUEST_OPTIONS = 7
SET_OPTIONS = 8
EXEC_CODE = 9
UPDATE_SELF = 10
DEPLOY_GAME = 11
REQUEST_SUBPROCESS_LOG = 12
DOWNLOAD_CERTIFICATES = 13
BACKUP_DATABASE = 14
COMMAND_NAMES = {
  0: 'CREATE_SERVER',
  1: 'DELETE_SERVERS',
  2: 'START_SERVERS',
  3: 'STOP_SERVERS',
  4: 'LIST_SERVERS',
  5: 'REQUEST_LOG',
  6: 'RENAME_AI',
  7: 'REQUEST_OPTIONS',
  8: 'SET_OPTIONS',
  9: 'EXEC_CODE',
  10: 'UPDATE_SELF',
  11: 'DEPLOY_GAME',
  12: 'REQUEST_SUBPROCESS_LOG',
  13: 'DOWNLOAD_CERTIFICATES',
  14: 'BACKUP_DATABASE'
}